import{a as L,S}from"./assets/vendor-DTDtTuz9.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&l(c)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const b="50250137-e72b1c1fd22aec0efc68e5be3",v="https://pixabay.com/api/",w=15;async function d(r,t){return(await L.get(v,{params:{key:b,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:w}})).data}const u=document.querySelector(".gallery"),f=document.querySelector(".load-more"),p=document.querySelector(".loader");let q=new S(".gallery a",{captionsData:"alt",captionDelay:250});function y(r){const t=r.map(n=>`
    <a href="${n.largeImageURL}" class="gallery-item">
      <img src="${n.webformatURL}" alt="${n.tags}" />
      <div class="info">
        <p><strong>Likes:</strong> ${n.likes}</p>
        <p><strong>Views:</strong> ${n.views}</p>
        <p><strong>Comments:</strong> ${n.comments}</p>
        <p><strong>Downloads:</strong> ${n.downloads}</p>
      </div>
    </a>
  `).join("");u.insertAdjacentHTML("beforeend",t),q.refresh()}function E(){u.innerHTML=""}function m(){p.classList.remove("hidden")}function h(){p.classList.add("hidden")}function P(){f.classList.remove("hidden")}function g(){f.classList.add("hidden")}const $=document.querySelector(".search-form"),M=document.querySelector(".gallery"),A=document.querySelector(".load-more");document.querySelector(".loader");const B=document.querySelector(".search-input");let a=1,s="",i=0;$.addEventListener("submit",async r=>{if(r.preventDefault(),s=B.value.trim(),s!==""){E(),g(),a=1,m();try{const t=await d(s,a);if(i=t.totalHits,t.hits.length===0){iziToast.info({message:"No images found. Try another search.",position:"topRight"});return}y(t.hits),i>15&&P()}catch(t){console.error(t)}finally{h()}}});A.addEventListener("click",async()=>{a+=1,m();try{const r=await d(s,a);y(r.hits),M.querySelectorAll(".gallery-item").length>=i&&(g(),iziToast.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(r){console.error(r)}finally{h()}});
//# sourceMappingURL=index.js.map
