import{S,i as a}from"./assets/vendor-Cau1Iyua.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const u of s.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&n(u)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();const b="50250137-e72b1c1fd22aec0efc68e5be3",v="https://pixabay.com/api/",R=15;async function m(t,o){const r=new URLSearchParams({key:b,q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",page:o,per_page:R}),n=await fetch(`${v}?${r}`);if(!n.ok)throw new Error("Failed to fetch images");return await n.json()}const q=document.querySelector(".gallery"),h=document.querySelector(".loader"),p=document.querySelector(".load-more"),E=new S(".gallery a",{captionsData:"alt",captionDelay:250});function g(t){const o=t.map(r=>`
    <a href="${r.largeImageURL}" class="gallery-item">
      <img src="${r.webformatURL}" alt="${r.tags}" />
      <div class="info">
        <p><strong>Likes:</strong> ${r.likes}</p>
        <p><strong>Views:</strong> ${r.views}</p>
        <p><strong>Comments:</strong> ${r.comments}</p>
        <p><strong>Downloads:</strong> ${r.downloads}</p>
      </div>
    </a>
  `).join("");document.querySelector(".gallery").insertAdjacentHTML("beforeend",o),E.refresh()}function $(){q.innerHTML=""}function y(){h.classList.remove("hidden")}function L(){h.classList.add("hidden")}function w(){p.classList.remove("hidden")}function i(){p.classList.add("hidden")}const B=document.querySelector("#search-form"),P=document.querySelector(".load-more");let l="",d=1,f=0,c=0;B.addEventListener("submit",async t=>{if(t.preventDefault(),l=t.target.elements.searchQuery.value.trim(),!!l){d=1,c=0,$(),i(),y();try{const o=await m(l,d);if(f=o.totalHits,o.hits.length===0){a.info({message:"No images found.",position:"topRight"}),i();return}g(o.hits),c+=o.hits.length,c<f?w():(i(),a.info({message:"End of search results.",position:"topRight"}))}catch(o){a.error({message:o.message,position:"topRight"})}finally{L()}}});P.addEventListener("click",async()=>{d+=1,y(),i();try{const t=await m(l,d);g(t.hits),c+=t.hits.length,M(),c<f?w():(i(),a.info({message:"End of search results.",position:"topRight"}))}catch(t){a.error({message:t.message,position:"topRight"})}finally{L()}});function M(){const{height:t}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
