import{a as S,S as b,i as l}from"./assets/vendor-C9vNCoLC.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))u(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&u(i)}).observe(document,{childList:!0,subtree:!0});function n(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function u(t){if(t.ep)return;t.ep=!0;const r=n(t);fetch(t.href,r)}})();const v="50250137-e72b1c1fd22aec0efc68e5be3",q="https://pixabay.com/api/",P=15;async function f(o,e){return(await S.get(q,{params:{key:v,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:P}})).data}const g=document.querySelector(".gallery"),m=document.querySelector(".load-more"),y=document.querySelector(".loader");let B=new b(".gallery a",{captionsData:"alt",captionDelay:250});function p(o){const e=o.map(n=>`
    <a href="${n.largeImageURL}" class="gallery-item">
      <img src="${n.webformatURL}" alt="${n.tags}" />
      <div class="info">
        <p><strong>Likes:</strong> ${n.likes}</p>
        <p><strong>Views:</strong> ${n.views}</p>
        <p><strong>Comments:</strong> ${n.comments}</p>
        <p><strong>Downloads:</strong> ${n.downloads}</p>
      </div>
    </a>
  `).join("");g.insertAdjacentHTML("beforeend",e),B.refresh()}function E(){g.innerHTML=""}function h(){y.classList.remove("hidden")}function L(){y.classList.add("hidden")}function R(){m.classList.remove("hidden")}function w(){m.classList.add("hidden")}const $=document.querySelector(".search-form"),M=document.querySelector(".gallery"),A=document.querySelector(".load-more");document.querySelector(".loader");const I=document.querySelector(".search-input");let a=1,s="",d=0,c=!1;$.addEventListener("submit",async o=>{if(o.preventDefault(),s=I.value.trim(),s!==""){E(),w(),a=1,h();try{const e=await f(s,a);if(d=e.totalHits,e.hits.length===0){l.info({message:"No images found. Try another search.",position:"topRight"});return}p(e.hits),d>15&&R()}catch(e){console.error(e)}finally{L()}}});A.addEventListener("click",async()=>{if(!c){c=!0,a+=1,h();try{const o=await f(s,a);p(o.hits),M.querySelectorAll(".gallery-item").length>=d&&(w(),l.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),O()}catch{l.error({message:"Something went wrong. Please try again.",position:"topRight"})}finally{c=!1,L()}}});function O(){const o=document.querySelector(".gallery-item");if(!o)return;const{height:e}=o.getBoundingClientRect();window.scrollBy({top:e*1.5,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
